// <auto-generated />
namespace website_projexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class finalfinal9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finalfinal9));
        
        string IMigrationMetadata.Id
        {
            get { return "202311201215413_finalfinal9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
